### ISSUE TITLE
Option to rerun the content provider function every build

### ISSUE THREAD

**Issue by OoDeLally** [rollup/rollup-plugin-replace#27]
```js
{
  //...
  watch: {
    input: [
      // ...
      './src/fileToInject.txt',
    ],
  },
  plugins: [
    // ...
    replace({
        __PLACEHOLDER__: (data) => {
          return fs.readFileSync('./src/fileToInject.txt', 'utf-8')
        },
    })
  ],
}
```
# Expected result:
Everytime I modify `fileToInject.txt`, I would like my bundle to be updated with the latest content.

# Current result:
Currently the function is evaluated only once at the first build. When the watcher detects a change, the bundle is rebuilt, but the `replace` plugin reuse the last value returned by the function. Therefore my bundle is not updated.

# Solution:
Provide a `evaluateEveryTime` or such option.

**Comment by pyrodogg** [comment]
I just spent a few minutes scratching my head as to why my `__BUILD_TIME__` replacement string wasn't getting updated as expected when using watch. As mentioned above, the replacement string was only evaluated if the watcher was restarted.

**Comment by pyrodogg** [comment]
I think the issue we're seeing is related to #6. 

This plugin implements the replacements in the transform hook, which is only evaluated for changed modules in watch mode. [[1]](https://rollupjs.org/guide/en#transform)

Therefore, if you changed the `fileToInject.txt` file, it would rebuild and transform that module only, not whichever module the `__PLACEHOLDER__` string is in. If you did change the module with `__PLACEHOLDER__` in it, it would bring in the updated texts from your file. Replacement functions are evaluated at each transformation.

What #6 proposes is processing the replacements after the bundle is generated. This would effectively reprocess the string replacements after modules have been individually transformed, and cached in watch mode. This means no matter which watched file is changed the replacements would be reevaluated.

It doesn't make sense to completely switch the plugin to be implemented in the renderChunk hook, but it would be nice to optionally specify certain replacements to run there instead of in transform hook.

**Comment by wesleygrimes** [comment]
Hey folks. This is a saved-form message, but rest assured we mean every word. The Rollup team is attempting to clean up the Issues backlog in the hopes that the active and still-needed, still-relevant issues bubble up to the surface. With that, we're closing issues that have been open for an eon or two, and have gone stale like pirate hard-tack without activity.

We really appreciate the folks have taken the time to open and comment on this issue. Please don't confuse this closure with us not caring or dismissing your issue, feature request, discussion, or report. The issue will still be here, just in a closed state. If the issue pertains to a bug, please re-test for the bug on the latest version of Rollup and if present, please tag @wesleygrimes and request a re-open, and we'll be happy to oblige.
